version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.0
  codecov: codecov/codecov@1.1.1
jobs:
  build:
    docker:
      - image: cimg/node:15.3.0-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install
          command: npm ci
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm run test:ci
      - store_artifacts:
          path: coverage/gallery/lcov.info
      - codecov/upload:
          file: coverage/gallery/lcov.info
workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
